# Generated by Django 5.2.8 on 2025-11-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacsv',
            name='equipment_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
