# Generated by Django 5.2.8 on 2025-11-14 19:26

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datacsv_equipment_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacsv',
            name='csv_file',
            field=models.FileField(upload_to=api.models.user_csv_file_path),
        ),
        migrations.AlterUniqueTogether(
            name='datacsv',
            unique_together={('user', 'title')},
        ),
    ]
